### PR TITLE
Typescript overhaul

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
Migrate strategy to use typescript.  Expose non-promise methods if so desired to be used.

I also changed use of `Algorithm` to `Ucb`, to better fit with types, as well as a non-default export from the main library file, so that the naming stays intact.  This is a common practice with Typescript.  I hope you like these additions, but if you don't please let me know what you'd like corrected, I have no qualms in satisfying the intent of ensuring this package can be used by many, be them javascript, or typescript, and for maximum usability.

It should also be noted that the output of this project will be generated each time you publish to npm, via the `out` directory, which is standard practice for typescript.

One loss of functionality I wasn't able to preserve is the use of `const instance = Algorithm(options)`.   I didn't see any possible way to provide that functionality without carrying a lot of custom code, and because it wasn't documented, I left it out.  I also removed a lot of the debug lines, I felt that debugging has sufficiently been solved with this project, and the only reason we'd need it is to do some profiling, which can easily be done with a standard IDE.

Thank you again for your fine original project!

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
As far as a use case goes: https://github.com/BKKnights/prosper-ucb-mongoose uses this as an example to the world.  More specifically: https://github.com/BKKnights/prosper-ucb-mongoose/blob/main/src/experiment.ts#L99

**Comment by kurttheviking** [comment]
Generally this looks OK though I'm curious why `const instance = Algorithm(options)` was dropped. At least the intent there in the spec is to preserve state restoration for a model -- namely to reload a model that was previously serialized with `ucb.serialize()`. Or are you saying that's possible with a different approach?

**Comment by robertleeplummerjr** [comment]
You'd just need to instantiate it by using `new`.  I couldn't find a straightforward way of doing both with and without `new`.

**Comment by robertleeplummerjr** [comment]
Any update or suggestions regarding this PR?  Busy lives.  If you feel anything should change prior to merging, I'm all ears.

Thanks again.

**Comment by kurttheviking** [comment]
I am currently traveling with limited access to wifi/cell service -- will review again when I'm back; sorry no OOO message setup for these repos :)

**Comment by robertleeplummerjr** [comment]
Again, thank you for your time @kurttheviking.  I'd love to get you eyes back on this when you have a moment.

**Comment by kurttheviking** [comment]
hey @robertleeplummerjr -- i wanted to resolve `npm audit` issues before merging your pr but before i merge this one wanted to make sure i didn't break any deps you were expecting; would you mind taking a look and letting me know

**Comment by robertleeplummerjr** [comment]
How we looking now?:

Current status from:
* `npm run test`
  Screenshot 2023-05-10 at 5 31 12 PM
* `npm run coverage`
  Screenshot 2023-05-10 at 5 30 54 PM
* Screenshot 2023-05-10 at 5 31 30 PM

**Comment by robertleeplummerjr** [comment]
bump

**Comment by robertleeplummerjr** [comment]
You rock.  If you are cool with it, [egreedy-js](https://github.com/kurttheviking/egreedy-js) is next.

**Comment by robertleeplummerjr** [comment]
Screenshot 2023-06-01 at 4 05 25 PM

Well that is depressing.

**Pull request merged**
